-- TCL
-- 멤버 테이블 -> 멤버 탈퇴 -> 탈퇴 테이블 데이터 저장
-- DELETE, INSERT
-- INSERT, UPDATE, DELETE
SELECT * FROM DEPARTMENT;
UPDATE DEPARTMENT
SET DEPT_TITLE = '전략기획팀'
WHERE DEPT_ID = 'D9';
ROLLBACK;

CREATE TABLE USERTRANSACTION(
    USER_NO NUMBER UNIQUE,
    USER_ID VARCHAR2(20) PRIMARY KEY,
    PASSWORD CHAR(20) NOT NULL
);

INSERT INTO USERTRANSACTION
VALUES (1, 'test1','pass01');
INSERT INTO USERTRANSACTION
VALUES (2, 'test2','pass02');
INSERT INTO USERTRANSACTION
VALUES (3, 'test3','pass03');

SELECT * FROM USERTRANSACTION;
COMMIT; -- 최종 저장
ROLLBACK;

INSERT INTO USERTRANSACTION
VALUES(4, 'test4', 'pass04');

-- SAVEPOINT
INSERT INTO USERTRANSACTION
VALUES(4, 'test4', 'pass04');
SAVEPOINT sp1; -- 임시저장 위치 설정
INSERT INTO USERTRANSACTION
VALUES(5, 'test5', 'pass05');
SELECT * FROM USERTRANSACTION;
ROLLBACK TO sp1;

---------------------------------------
-- DDL
CREATE TABLE MEMBER_TABLE(
    USER_NO NUMBER NOT NULL,
    USER_ID VARCHAR2(30) CONSTRAINT USER_ID_PK PRIMARY KEY,
    USER_PWD CHAR(20)
);
-- 컬럼 추가
ALTER TABLE MEMBER_TABLE ADD(USER_NAME VARCHAR2(20));
DESC MEMBER_TABLE;

-- 컬럼명 수정
ALTER TABLE MEMBER_TABLE RENAME COLUMN USER_PWD TO PASSWORD;
DESC MEMBER_TABLE;

-- 컬럼 자료형 수정
ALTER TABLE MEMBER_TABLE
MODIFY USER_NAME CHAR(10)
MODIFY PASSWORD VARCHAR2(20);
DESC MEMBER_TABLE;

-- 컬럼 삭제
ALTER TABLE MEMBER_TABLE DROP (USER_NAME);
DESC MEMBER_TABLE;
-- ALTER TABLE MEMBER_TABLE DROP (USER_ID PK CASCADE CONSTRAINT);

-- 제약조건
-- 제약조건 추가
ALTER TABLE MEMBER_TABLE ADD CONSTRAINT MEMBER_TB_ID_UNQ UNIQUE (PASSWORD);

-- 제약조건 삭제
ALTER TABLE MEMBER_TABLE DROP CONSTRAINT MEMBER_TB_ID_UNQ;

-- 제약조건 이름 변경
ALTER TABLE MEMBER_TABLE RENAME CONSTRAINT SYS_C007063 TO USER_NO_NOT_NULL;

-- NOT NULL 제약 조건 변경
ALTER TABLE MEMBER_TABLE MODIFY PASSWORD CONSTRAINT PWD_NOT_NULL NOT NULL;

-- 테이블
-- 테이블 이름 변경
RENAME MEMBER_TABLE TO MEMBER_TBL;
DESC MEMBER_TBL;
-- 테이블 삭제
DROP TABLE MEMBER_TBL;

-- DCL 데이터 제어어
-- GRANT 권한 할당
-- sys계정
CREATE USER KHUSER02 IDENTIFIED BY KHUSER02;
GRANT CONNECT, RESOURCE TO KHUSER02;

-- KH계정
CREATE TABLE COFFEE(
    PRODUCT_NAME VARCHAR2(20) PRIMARY KEY,
    PRICE NUMBER NOT NULL,
    COMPANY VARCHAR2(20) NOT NULL
);

DESC COFFEE;
INSERT INTO COFFEE VALUES('맥심커피', 30000, 'MAXIM');
INSERT INTO COFFEE VALUES('카누커피', 50000, 'MAXIM');
INSERT INTO COFFEE VALUES('네스카페커피', 40000, 'NESCAFE');
SELECT * FROM COFFEE;
COMMIT; -- COMMIT을 해주어야 다른 계정에서도 해당 데이터를 조회할 수 있다.

-- KHTEST계정
SELECT * FROM KH.COFFEE;

-- sys계정
GRANT SELECT ON KH.COFFEE TO KHTEST; -- SELECT 권한을 주어야 SELECT가 가능함.

-- KHTEST 계정
SELECT * FROM KH.COFFEE;

-- ex) KH계정의 테이블 데이터 입력 권한(INSERT)을 KHTEST에 부여 해보기
GRANT INSERT ON KH.COFFEE TO KHTEST;
--
INSERT INTO KH.COFFEE VALUES('민초', 20000, 'MINT');

REVOKE SELECT ON KH.COFFEE FROM KHTEST;


